name: Deploy Dist
on: [push,workflow_dispatch]

jobs: 
  test:
    runs-on: self-hosted #ubuntu-latest
    steps:
      - name: get code
        run: |
          echo "cloning repository..."
          echo "${{toJson(github)}}"
          git clone https://github.com/${{github.repository}}.git
